### ISSUE TITLE
directory for get_beam_emission_rate()

### ISSUE THREAD

**Issue by drsmith48** [cherab/openadas#14]
Directory should be `beam/emission`:
https://github.com/cherab/openadas/blob/fa4f46280dfccb1da424a42fd31e9f285d1d3e32/cherab/openadas/repository/beam/emission.py#L141

**Comment by CnlPepper** [comment]
Ooh that is a nasty copy-paste mistake. Thanks for spotting that, will fix this asap.

**Comment by mattngc** [comment]
Yeah, luckily it wasn't being used in any of the public models so the impact of the bug should be limited.
