### ISSUE TITLE
Incorrect ionisation stage for ADF11 rates

### ISSUE THREAD

**Issue by mattngc** [cherab/openadas#20]
@Mateasek believes CHERAB might be reading the wrong ionisation state from ADF11 files. He suggests the Z value in the files might mean the "recombining ion charge". i.e.  Currently you can read an ionization rate for neon 10, which is impossible.Therefore the ionisation rate in OpenADAS for Z=10 might actually mean Z=9. @mattngc might have miss interpreted the ADAS ADF11 documentation. Assigning to @Mateasek for investigation.

**Comment by Mateasek** [comment]
I will check if openadas way of notation is correctly interpreted. I know I had some troubles sorting it out in my head :-D

Just to clarify notation to be used in cherab:

- cherab uses arabic number notation of ionisation stages i.e. 0 is neutral and 1 is singly ionised ion
- ionisation rate of a stage x causes depletion of stage x and population of stage x+1
- recombination rate of a stage x causes depletion of stage x and population of stage x-1

**Comment by mattngc** [comment]
Yes this notation is correct, thanks @Mateasek.

**Comment by Mateasek** [comment]
I would suggest changing word ionisation used to denote charge of the ion to charge or chargestate. Word ionisation is in my opinion the atomic process and could sometimes lead to confusion. Problem is it is used throughout quite some part of the code. What do you think?

**Comment by mattngc** [comment]
Yeah, I think we would need to think more about this kind of change. As you point out, the reason I used `ionisation` here is because its become a bit of a convention and used widely throughout the code. Changing it is certianly not out of the question but we should think carefully before doing it as we would need to change the convention everywhere. `charge` or `charge_state` is certainly just as clear as ionisation, and may indeed be clearer if we want to distinguish from the process of ionisation. I'll discuss with @CnlPepper and @jacklovell in person next week to see what the consensus opinion is. But this would be tracked in a different issue anyway, because its a bigger refactor.

**Comment by mattngc** [comment]
@Mateasek, see the example calculation from @jacklovell in https://github.com/cherab/mastu/issues/6. Seems to confirm your hypothesis about the bug.

**Comment by Mateasek** [comment]
Just to keep track....
OpenAdas denotes charge states in data headers as recombining ion charge (viz documentation for each file and fortran reading routines)

- IZ1recombining ion charge (Z1 in data headers)
- IZ1MIN - lowest ion charge +1, IZ1MAX - highest ion charge


ADF11 stored rates and notes: 
1. **acd** Effective Recombination Coefficients
    - recombination rate from charge n to n-1
    - Z1 e [1, Zmax]
    - electron recombination of charge 0 (neutral) is neglected (no negative ions)
    - correction from adas to cherab: charge = Z1
2.  **scd** - Effective Ionisation Coefficients
    - ionization rate from charge n to n+1
    - Z1 e [1, Zmax]
    - ionisation of state charge=Zmax (absolutely stripped ion) is impossible
    - correction from adas to cherab: charge = Z1 -1
3. **ccd** - CX Cross Coupling Coefficients 
    - CX Between neutra hydrogen species and charge n
    - Z e [1, Zmax]
    - CX of H with charge 0 (neutral) is neglected (no negative ions)
    - correction from adas to cherab: charge = Z1 -1
4. **plt** - Line Emission from excitation
    - line radiated power by charge n by electron impact excitation
    -  Z1 e [1, Zmax]
    - radiation by state charge=Zmax (absolutely stripped ion) is impossible
    - correction from adas to cherab: charge = Z1 -1
5. prb - Recombination and Bremsstrahlung
    - radiated power by bremsstrahlung and and line rdiation due to recombination of charge n
    - Z1 e [1, Zmax]
    - radiation by recombination of charge 0 (neutral) is neglected (no negative ions)
    - correction from adas to cherab: charge = Z1
6. **prc** - Charge exchange PLS - Specific line
    - line radiated power by CX of H with charge state
    - Z e [1, Zmax]
    - CX of H with charge 0 (neutral) is neglected (no negative ions)
    - correction from adas to cherab: charge = Z1

7. **pls** - Specific line
    - specific line radiated power by charge n by electron impact excitation
    -  Z1 e [1, Zmax]
    - radiation by state charge=Zmax (absolutely stripped ion) is impossible
    - correction from adas to cherab: charge = Z1 -1

**Comment by CnlPepper** [comment]
Quick comment re the use of ionisation, when I originally used this it was because we tended to refer to the ion charge as ionisation level. I agree this is now causing an unfortunate clash between this attribute and the process. After some consideration, I think I'm leaning towards renaming the attribute to charge as @mateasek suggests. Given how widely it is used, this would be a major API change... but this can be managed. We could make the change to charge and for the next few releases leave the ionisation attribute in place, but make it raises an exception that informs the user to update their code.

**Comment by Mateasek** [comment]
This commmit 47d8ef99c64f4587ac9257b93109655ba9b31414 is a sketch of solution for the wrongly interpreted charge states. I added an additional function "rates_adf11" which does the remapping from adas to cherab charge notation and is supposed to be called during repository creation/updates instead of directly old parse_adf11 (which stayed). I chose this solution because it preserves the possibility to have adf11 files parsed and kept with original notation. It just has more versatility. Could @mattngc and @CnlPepper  please look at it and tell me whether this is the right way to go?

The problem with the calculation of the ionisation balance wasn't fixed tho. I crosschecked the matrix with adas documentation and it seems correct now. I will check if the rates are correctly interpolated in next step.

**Comment by CnlPepper** [comment]
@Mateasek  Thanks for the sketch. I'd move the conversion routine to the individual adf11 install functions, not place it inside the parse module. The parse module methods return the contents of the ADF files in a form consistent with the original files (baring the odd unit conversion). The data cherab writes via the update_* methods in the cherab repo are our own derived specification. The install methods are the point where any modification of representation or missing meta data should be added.

@mattngc btw when looking through the cherab repo update functions I found this method:https://github.com/cherab/openadas/blob/81b0eaa8f43009439dca91789f2a2d0bec5cce3a/cherab/openadas/repository/radiated_power.py#L156
Could you remove the _adf11 bit, these are cherab's derived/extended representations not the raw files. Given we will be modifying the ion charge value for some rates this is now even more of a misnomer.

When I designed the package the install section is essentially a "firewall" between the two representations: ADF rate representation -> install methods -> cherab rate representations
To keep the code maintainable it would be good if we can continue to be strict with the layer separation.

**Comment by Mateasek** [comment]
An update to the state of the inoization balance calculation. I commited a few new changes in b271bce which can hopefully explain why there were some problems with the ionization balance calculations. File 
[ratescheck.py](https://github.com/Mateasek/cherab_openadas/blob/b271bce072c585b1c57073b1fa0817525d65df79/demos/ratescheck.py) compares 3 different ways of interpolations. Please have in mynd that if you want to run it you have to do a clear population of your rates repository.

There are three ways of interpolation shown using cherab 2d interpolators for consistency:
1. Interpolation on original openadas database temperature, density and rate data in their original log10 representation. The rates are then brought to correct units.
2. Interpolation on original openadas database temperature, density and rate data in normal (10 ** data) representation. The rates are then brought to correct units.
3. Interpolation using built-in cherab functions

The results are shown in these plots:
![ionrates_compare](https://user-images.githubusercontent.com/969455/54680644-ab777680-4b0a-11e9-8252-9ad3b03d03b2.png)
![recomrates_compare](https://user-images.githubusercontent.com/969455/54680651-b16d5780-4b0a-11e9-8633-54b49a3c91b9.png)
![ionbal_compare](https://user-images.githubusercontent.com/969455/54680656-b3cfb180-4b0a-11e9-9ada-c15116436371.png)

The balance matrix seems to be correct, but we could use some data calculated by adas codes to benchmark/compare with. Anyway, it can be seen that cherab interpolators fail to cope with adas data in normal (10 ** data) format. The rates chage by 50 orders of magnitude, the temperature and density data by a bit less. I hope I haven't overlooked any bug in my code, but I am afraid it would be better to store and interpolate data in log10 format and transform the results after interpolation. After all ADAS is probably storing it in log10 format for a reason, what do you think? Could @mattngc and @CnlPepper have a look? Cheers

**Comment by CnlPepper** [comment]
The interpolators should be fine interpolating over that range of magnitudes in real space. However I have recently also noticed an issue with the implementation failing for larger ranges, ranges that currently fall outside the unit tests.

As @mattngc knows, there are some improvements to the interpolator implementation that I would like to make. These changes should make them more stable for large dynamic ranges and faster to execute. I pretty sure the issue lies with the use of the scipy solve routine, which our student used in the implementation. The values he is solving for can be precalculated and applied to the array data rather than preparing the data and solving directly. I really wasn't expecting to see an issue in the wild, unfortunately it looks like this will have to be fixed asap.

It may be easier to store the log rates for now. But I do hate log interpolation, it does stupid things to the data shape.

**Comment by Mateasek** [comment]
What about changing https://github.com/cherab/openadas/blob/0f5cc2560238f9e4fb5970d7e852854b6e45b671/cherab/openadas/rates/atomic.pyx#L21
and 
https://github.com/cherab/openadas/blob/0f5cc2560238f9e4fb5970d7e852854b6e45b671/cherab/openadas/rates/atomic.pyx#L61
and etc. 

For now before the interpolators are upgraded? The 2d interpolator within the instance could be working on a log10 format and could be converting rates befoere returning them. This way the rates repository can stay untouched and it can be removed easily after interpolators are enhaced.

**Comment by mattngc** [comment]
I agree with the changes proposed by @Mateasek. Most sensible approach seems to be to store the rates in log10 format. The implemented rates objects in OpenADAS perform the interpolation in log10 space and then convert the rate back to linear space when returning.

**Comment by Mateasek** [comment]
In my opinion for now the simplest and most general solution is to store the data in linear form and constructing the interpolators on the log10 format and making the power before the vaule is returned to the user. The te and ne data can be in linear form. This way the ideology of the rate db will stay consistent with other data and it can be easily removed when the interpolators are enhanced. This is for me the fastest and most consistent fix. I will proceed with this in the frac_abundance branch to move forward and if @mattngc and @CnlPepper like the solution we can also merge it to development when fractional abundance is ready.

**Comment by CnlPepper** [comment]
Sounds good, butlease don't mix this change in with others, ot makes code reviewing difficult. It should be a separate pull request.

**Comment by mattngc** [comment]
Thanks for this work @Mateasek. I also agree with the approach you have suggested.

I agree with Alex though, be careful about mixing different issues. From experience, I find the best approach with big code development is to keep changes in feature branches small and targeted to specific issues. That way its very easy to work on them separately and merge them without conflicts. If you do lots of different changes in one branch the changes can become very bloated and a mix of different functionality. It then becomes more difficult to merge.

**Comment by mattngc** [comment]
For example, the change discussed in this issue is completely independent of the new CCD rates. You could easily make this fix to the existing ADF11 rates, close this issue and then work on the new CCD rates separately.

**Comment by Mateasek** [comment]
I will make a separate issue and branch for the interpolation.

**Comment by Mateasek** [comment]
A part of the fix, namely for the charge notation problem, is in the PR #29

**Comment by mattngc** [comment]
This bug has now been closed with the merge of PR #29. A number of related issues will persist.
