### ISSUE TITLE
Add adf11 ccd rates: charge exchange rates between element and neutral hydrogen

### ISSUE THREAD

**Issue by Mateasek** [cherab/openadas#25]
I have notticed that the ADF11 rates are still missing in cherab database. It would be nice if we could add it so it is implemented in the ionization balance calculations? May I try?

**Comment by mattngc** [comment]
Sure, it would be great to have this added. Happy to have you contribute it.

**Comment by mattngc** [comment]
This issue is being addressed in PR #26.

**Comment by mattngc** [comment]
Resolved in PR #26.
