### ISSUE TITLE
ADF11acd, scd, ccd interpolators working in log10 space

### ISSUE THREAD

**Issue by Mateasek** [cherab/openadas#27]
Interpolators for openadas ADF11 atomic data should now work in log10 space to get closer to adas and to remove some numerical troubles present in today version of interpolators.

I would like to apply the conversions into atomic classes in [atomic.pyx](https://github.com/cherab/openadas/blob/feature/frac_abundance/cherab/openadas/rates/atomic.pyx). This way the rate database whill stay consistent and untouched.

This change would be probably best to be made after I get the PR #26 accepted, because it will also include changing thermal cx rate interpolation.

**Comment by mattngc** [comment]
Resolved with PR #33.
