### ISSUE TITLE
pip install cherab-openadas setup.py egg_info error 

### ISSUE THREAD

**Issue by simbouwmans** [cherab/openadas#43]
Hey, 

I tried installing the cherab-openadas error and keep on getting this error:

ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nnvvcpj5/cherab-openadas/

If I only use pip install cherab -- user, everything works fine but the openadas extention with, pip install cherab-openadas --user, will fail. Any info on how to fix this as this also happens with the seperate setup.py from github? The full error is given below:

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: 
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # CONDITIONS OF ANY KIND, either express or implied.
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.
    
    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:19:0: 'cherab/core.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # CONDITIONS OF ANY KIND, either express or implied.
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.
    
    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:19:0: 'cherab/core/ImpactExcitationRate.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.
    
    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:20:0: 'cherab/core/RecombinationRate.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.
    
    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:21:0: 'cherab/core/ThermalCXRate.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # under the Licence.
    
    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    from cherab.core.math cimport Interpolate2DCubic
    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:22:0: 'cherab/core/math.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # under the Licence.
    
    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    from cherab.core.math cimport Interpolate2DCubic
    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:22:0: 'cherab/core/math/Interpolate2DCubic.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    from cherab.core.math cimport Interpolate2DCubic
    
    
    cdef class ImpactExcitationRate(CoreImpactExcitationRate):
                                   ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:25:32: First base of 'ImpactExcitationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef:
            readonly dict raw_data
            readonly double wavelength
            readonly tuple density_range, temperature_range
            Interpolate2DCubic _rate
           ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:31:8: 'Interpolate2DCubic' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            readonly double wavelength
            readonly tuple density_range, temperature_range
            Interpolate2DCubic _rate
    
    
    cdef class NullImpactExcitationRate(CoreImpactExcitationRate):
                                       ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:34:36: First base of 'NullImpactExcitationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cdef class NullImpactExcitationRate(CoreImpactExcitationRate):
        pass
    
    
    cdef class RecombinationRate(CoreRecombinationRate):
                                ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:38:29: First base of 'RecombinationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef:
            readonly dict raw_data
            readonly double wavelength
            readonly tuple density_range, temperature_range
            Interpolate2DCubic _rate
           ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:44:8: 'Interpolate2DCubic' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            readonly double wavelength
            readonly tuple density_range, temperature_range
            Interpolate2DCubic _rate
    
    
    cdef class NullRecombinationRate(CoreRecombinationRate):
                                    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pxd:47:33: First base of 'NullRecombinationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import matplotlib.pyplot as plt
    
    from cherab.core.utility.conversion import PhotonToJ
    
    
    cdef class ImpactExcitationRate(CoreImpactExcitationRate):
                                   ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:26:32: First base of 'ImpactExcitationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # interpolate rate
            self._rate = Interpolate2DCubic(
                ne, te, rate, extrapolate=extrapolate, extrapolation_type="quadratic"
            )
    
        cpdef double evaluate(self, double density, double temperature) except? -1e999:
             ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:55:10: C method 'evaluate' not previously declared in definition part of extension type 'ImpactExcitationRate'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
            # prevent -ve values (possible if extrapolation enabled)
            return max(0, self._rate.evaluate(density, temperature))
    
    
    cdef class NullImpactExcitationRate(CoreImpactExcitationRate):
                                       ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:61:36: First base of 'NullImpactExcitationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        A PEC rate that always returns zero.
        Needed for use cases where the required atomic data is missing.
        """
    
        cpdef double evaluate(self, double density, double temperature) except? -1e999:
             ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:67:10: C method 'evaluate' not previously declared in definition part of extension type 'NullImpactExcitationRate'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cpdef double evaluate(self, double density, double temperature) except? -1e999:
            return 0.0
    
    
    cdef class RecombinationRate(CoreRecombinationRate):
                                ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:71:29: First base of 'RecombinationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            self._rate = Interpolate2DCubic(
                ne, te, rate, extrapolate=extrapolate, extrapolation_type="quadratic"
            )
    
    
        cpdef double evaluate(self, double density, double temperature) except? -1e999:
             ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:101:10: C method 'evaluate' not previously declared in definition part of extension type 'RecombinationRate'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
            # prevent -ve values (possible if extrapolation enabled)
            return max(0, self._rate.evaluate(density, temperature))
    
    
    cdef class NullRecombinationRate(CoreRecombinationRate):
                                    ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:107:33: First base of 'NullRecombinationRate' is not an extension type
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        A PEC rate that always returns zero.
        Needed for use cases where the required atomic data is missing.
        """
    
        cpdef double evaluate(self, double density, double temperature) except? -1e999:
             ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:113:10: C method 'evaluate' not previously declared in definition part of extension type 'NullRecombinationRate'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # store limits of data
            self.density_range = ne.min(), ne.max()
            self.temperature_range = te.min(), te.max()
    
            # interpolate rate
            self._rate = Interpolate2DCubic(
                        ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:51:21: 'Interpolate2DCubic' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # store limits of data
            self.density_range = ne.min(), ne.max()
            self.temperature_range = te.min(), te.max()
    
            # interpolate rate
            self._rate = Interpolate2DCubic(
                        ^
    ------------------------------------------------------------
    
    cherab/openadas/rates/pec.pyx:96:21: 'Interpolate2DCubic' is not a constant, variable or function identifier
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iixu7p2_/cherab-openadas/setup.py", line 55, in <module>
        extensions = cythonize(extensions, nthreads=multiprocessing.cpu_count(), force=force, compiler_directives=cython_directives)
      File "/home/s147706/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
        cythonize_one(*args)
      File "/home/s147706/.local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: cherab/openadas/rates/pec.pyx
    Compiling cherab/openadas/rates/pec.pyx because it depends on /home/s147706/.local/lib/python3.7/site-packages/Cython/Includes/numpy/__init__.pxd.
    [1/1] Cythonizing cherab/openadas/rates/pec.pyx
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-iixu7p2_/cherab-openadas/

**Comment by CnlPepper** [comment]
Hi @simbouwmans, we've started seeing this issue with other users recently. It appears to be a combination of an update to pip/setup tools which now uses PEP420 namespaces and the lack of PEP420 namespace support in Cython. I've had a merge request accepted for Cython 3.0 (https://github.com/cython/cython/pull/2946) which fixes the issue. If you are willing to use the current development version of cython and you reinstall the raysect, cherab (core) and openadas packages then it should install correctly.

To install the latest version of cython, checkout the head revision of their development repository and install it:
```
git clone https://github.com/cython/cython.git
cd cython
python setup.py install --user
```
Then remove and reinstall raysect and cherab:

```
pip uninstall cherab-openadas
pip uninstall cherab
pip uninstall raysect 

# I'm disabling the cache to ensure it rebuilds from source
pip install raysect --no-cache-dir
pip install cherab --no-cache-dir
pip install cherab-openadas --no-cache-dir
```

This workaround will be unnecessary once the Cython team releases version 3.0.

**Comment by simbouwmans** [comment]
Thanks for the respond, however exactly the same error occurs even with the cython package that is manually downloaded from https://github.com/cython/cython which should be their development repository

**Comment by CnlPepper** [comment]
That is a little troubling. Could you do me a favour and double check the correct cython version is being picked up by typing:
```
cython --version
```
I'll create a VM tonight and double check everything from scratch in a clean environment.

**Comment by simbouwmans** [comment]
The cython version is 0.29.12

**Comment by CnlPepper** [comment]
Ah that is still the old version. I suspect your .local/bin directory is not in the path. Try typing:

```
export PATH=$HOME/.local/bin:$PATH
```
then check the cython version.

If this reports version 3 then the local path is not set byt default on your OS. Add the line above to your .bashrc file and close and reopen any terminals. Then try reinstalling raysect and cherab as above.

**Comment by mattngc** [comment]
Hey @simbouwmans, did you get this working? Can I assume the issue is fixed? I believe @CnlPepper submitted a patch to Cython to fix these issues.
